name: Saucedemo Web UI Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  saucedemo-web-ui-automation:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # download repository
      - uses: actions/checkout@v4

      # setup java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # install browser
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2.1.0
      
      # setup gradlew
      - name: Setup gradlew
        run: chmod +x gradlew

      # Execute the Gradle command for running tests
      - name: Execute Test
        run: ./gradlew test
      
      # Archive Test Result
      - name: Archive Test Result
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: Reqres API Report Test
          path: build/reports/
      
      # Deploy to Github Pages
      - name: Deploy report to Github Pages
        if: always()      
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          name: test-report
          github_token: ${{ secrets.GITHUB_TOKEN}}
          publish_dir: reports
